### ISSUE TITLE
[Bugs] Cannot run on Windows

### ISSUE THREAD

**Issue by axmad386** [kodepandai/lunox#14]
Currently lunox can't run on windows. I don't have windows to test it, but my friend try to run and fail 😞

**Comment by damarsimple** [comment]
![Cuplikan layar 2022-03-19 150727](https://user-images.githubusercontent.com/10891460/159115120-3a690377-5ba8-415c-8aba-d063696ca75e.png)

it can run on windows if  run the script directly 
for some reason it not using node to run the script instead rely on windows open file extension default configuration

**Comment by axmad386** [comment]
@damarsimple is it can run command `lunox watch`? Or `node node_modules\lunox\bin\lunox.cjs watch`
I test it before and errors happen. I think it is because difference between windows and unix system path separator. 
For example 
```js
// in unix or unix like system
import("../somepath/module.js")
// in windows it should be
import("..\\somepath\\module.js")
```

It should be easy for fixing this with `path.sep`, but I don't use windows to test it :disappointed:

**Comment by damarsimple** [comment]
![image](https://user-images.githubusercontent.com/10891460/159116984-39a72ac5-336b-4049-abff-46f871d576de.png)

@axmad386  i digging it little bit more i managed to run it with node using yarn lunox / npm run lunox by manually changing file

node_modules/.bin/lunox.cmd

from 

`@"%~dp0\..\lunox\bin\lunox.cjs"   %*`

to 

`@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\lunox\bin\lunox.cjs" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\lunox\bin\lunox.cjs" %*
)`

i dont think its path.sep issue tbh.
more of binary generation ? or the stuff that responsible for generating the cmd file
the default for other package is using nodejs to run the script while yours not.

**Comment by axmad386** [comment]
Wow. Thanks @damarsimple for your experiments. But how to compile that binnary. For now I using rollup to compile lunox code base. PR is welcome :smiley:

**Comment by damarsimple** [comment]
![image](https://user-images.githubusercontent.com/10891460/159127199-35407870-f157-4c2e-9966-7f192851afe8.png)
![image](https://user-images.githubusercontent.com/10891460/159127839-2a011e12-279d-4f2b-b195-a084248bcd39.png)

I managed to make it run on windows and linux using my fork

lunox-framework : https://github.com/damarsimple/lunox-framework

lunox-repos : https://github.com/damarsimple/my-lunox-app

Temporary Fix :
- Remove clean and fix on the build command (rm command not exists on cmd?)

Steps : 
- Adding bin folder to repo (remove /bin from gitignore)
- Create lunox bin file in bin folder
- set the bin from "./bin/lunox.cjs" to "./bin/lunox." in package.json
- set rollup output from "./bin/lunox.cjs" to "./bin/lunox.js"
- remove type  : module  from package.json (nodejs cant recognize /bin/lunox file extension if type set to module)
- add prepare script to package.json

By doing steps above nodejs managed to create runnable binary script on windows
I believe this is due to wrong package.json configuration? resulting to wrong binary script for windows

I'm not sure tbh because i never make nodejs package 😂.

**Comment by axmad386** [comment]
@damarsimple I am not sure, but `type: module` should not be deleted because of lunox codebase using esm syntax. I think it will break many things when we run `lunox watch` or `lunox prod` in sekeleton app.
Can you submit PR? I will check it when I got access to windows system.

**Comment by damarsimple** [comment]
@axmad386  done sir you can check it on https://github.com/kodepandai/lunox-framework/pull/7

**Comment by axmad386** [comment]
> @axmad386 done sir you can check it on [kodepandai/lunox-framework#7](https://github.com/kodepandai/lunox-framework/pull/7)

OK, I think better we discuss on your PR :smiley:

**Comment by axmad386** [comment]
fixed on https://github.com/kodepandai/lunox-framework/pull/7
